#############################################
# Примеры записанных пакетов данных в виде списка байтов

package_1 = [
    b'\xfb',
    b'\x01',
    b'\xff',
    b'\x0c',
    b'\x7c',
    b'\x28',
    b'\x00',
    b'\x00',
    b'\x32',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x43',
    b'\x90',
    b'\xf5',
    b'\x3e',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x80',
    b'\xad',
    b'\x26',
    b'\x21',
    b'\x41',
    b'\x22',
    b'\xd1',
    b'\x06',
    b'\xbc',
    b'\x9a',
    b'\xfd',
    b'\x3e',
    b'\x3b',
    b'\xae',
    b'\xac',
    b'\xef',
    b'\x39',
    b'\xf4',
    b'\x40',
    b'\xe5',
    b'\x3e',
    b'\x60',
    b'\x8d',
    b'\x69',
    b'\x40',
    b'\xcc',
    b'\xcc',
    b'\x9c',
    b'\xc0',
    b'\xd0',
    b'\x0f',
    b'\x49',
    b'\x40',
    b'\x25'
]

package_2 = [
    b'\xfb',
    b'\x01',
    b'\xff',
    b'\x0c',
    b'\x7d',
    b'\x28',
    b'\x00',
    b'\x00',
    b'\x32',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x43',
    b'\x90',
    b'\xf5',
    b'\x3e',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x80',
    b'\xad',
    b'\x26',
    b'\x21',
    b'\x41',
    b'\x22',
    b'\xd1',
    b'\x06',
    b'\xbc',
    b'\x9a',
    b'\xfd',
    b'\x3e',
    b'\x3b',
    b'\xae',
    b'\xac',
    b'\xef',
    b'\x39',
    b'\xf4',
    b'\x40',
    b'\xe5',
    b'\x3e',
    b'\x60',
    b'\x8d',
    b'\x69',
    b'\x40',
    b'\xcc',
    b'\xcc',
    b'\x9c',
    b'\xc0',
    b'\xd0',
    b'\x0f',
    b'\x49',
    b'\x40',
    b'\x2d'
]

package_3 = [
    b'\xfb',
    b'\x01',
    b'\xff',
    b'\x0c',
    b'\x7e',
    b'\x28',
    b'\x00',
    b'\x00',
    b'\x32',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x43',
    b'\x90',
    b'\x75',
    b'\x3e',
    b'\x43',
    b'\x90',
    b'\xf5',
    b'\xbd',
    b'\x8c',
    b'\x3b',
    b'\x1f',
    b'\x41',
    b'\x93',
    b'\xec',
    b'\x13',
    b'\xbc',
    b'\x88',
    b'\x4e',
    b'\x0e',
    b'\x3b',
    b'\xb8',
    b'\xc6',
    b'\x24',
    b'\x3a',
    b'\x10',
    b'\x54',
    b'\xce',
    b'\x3e',
    b'\x60',
    b'\x8d',
    b'\x69',
    b'\x40',
    b'\xcc',
    b'\xcc',
    b'\x9c',
    b'\xc0',
    b'\xd0',
    b'\x0f',
    b'\x49',
    b'\x40',
    b'\xa2'
]

package_4 = [
    b'\x0c',
    b'\x90',
    b'\xbc',
    b'\xfb',
    b'\x01',
    b'\xff',
    b'\x0c',
    b'\x7c',
    b'\x28',
    b'\x00',
    b'\x00',
    b'\x32',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x43',
    b'\x90',
    b'\xf5',
    b'\x3e',
    b'\x00',
    b'\x00',
    b'\x00',
    b'\x80',
    b'\xad',
    b'\x26',
    b'\x21',
    b'\x41',
    b'\x22',
    b'\xd1',
    b'\x06',
    b'\xbc',
    b'\x9a',
    b'\xfd',
    b'\x3e',
    b'\x3b',
    b'\xae',
    b'\xac',
    b'\xef',
    b'\x39',
    b'\xf4',
    b'\x40',
    b'\xe5',
    b'\x3e',
    b'\x60',
    b'\x8d',
    b'\x69',
    b'\x40',
    b'\xcc',
    b'\xcc',
    b'\x9c',
    b'\xc0',
    b'\xd0',
    b'\x0f',
    b'\x49',
    b'\x40',
    b'\x25'
]

#############################################


# Функция для вывода в консоль пакета данных из строки
def str_to_package(package_string: str):
    str_bytes_list = package_string.split()

    for i in range(len(str_bytes_list)):
        if str_bytes_list[i] == '20':
            str_bytes_list[i] = '00'

        print(r"b'\x" + f"{str_bytes_list[i]}'", end='')

        if i != len(str_bytes_list) - 1:
            print(',')


# --------------------------------------------


if __name__ == '__main__':
    str_bytes = "fb 01 ff 0c 7e 28 20 20 32 20 20 20 43 90 75 3e 43 90 f5 bd 8c 3b 1f 41 93 ec 13 bc 88 4e 0e 3b b8 c6 24 3a 10 54 ce 3e 60 8d 69 40 cc cc 9c c0 d0 0f 49 40 a2  "
    str_to_package(str_bytes)

